### ISSUE TITLE
How to hide the Solaar icon in the top bar / system tray?

### ISSUE THREAD

**Issue by aeXi3** [sidevesh/solaar-gnome-extension#2]
Hi,

Solaar has an startup parameter to hide the system tray icon '--window=only'. Where do I have to add this parameter so no icon is shown when Gnome starts Solaar automatically?

Thanks for your help!

**Comment by sidevesh** [comment]
This extension does not manage Solaar but only provides a dbus interface to it for some apis on Gnome on Wayland desktop.
